### ISSUE TITLE
Add CONTRIBUTING.md file.

### ISSUE THREAD

**Issue by pedrovgs** [Karumi/FoursquareTop#20]
As every Karumi repository we should add our official ``CONTRIBUTING.md`` file showing the possible contributors how to contribute to this repository. @gragera if you think we should not accept external PR instead of adding the ``CONTRIBUTING.md`` file we should add a disclaimer in the project ``README.md``. What do you think?

**Comment by gragera** [comment]
We should have one, contributing would be nice :)

**Comment by pedrovgs** [comment]
I'll send you a PR with the one we are using for the rest of the projects :)
